[package]
name = "aws-auth"
version = "0.1.0"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "mfa", "2fa"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/jhandguy/aws-auth"
description = """
Authenticate to AWS with MFA 🔐
"""

[dependencies]
anyhow = "1.0.63"
aws-config = "0.47.0"
aws-sdk-sts = "0.17.0"
clap = { version = "3.2.17", features = ["derive", "env"] }
thiserror = "1.0.33"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
aws-smithy-client = { version = "0.47.0", features = ["test-util"]}
aws-smithy-http = "0.47.0"
http = "0.2.8"
