[package]
name = "aws-mfa"
version = "0.2.12"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "mfa", "2fa"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aws-mfa"
documentation = "https://docs.rs/aws-mfa"
description = """
Authenticate to AWS with MFA 🔐
"""

[lib]
name = "aws_mfa"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aws-mfa"
test = false
doc = false

[dependencies]
anyhow = "1.0.68"
aws-config = "0.54.1"
aws-sdk-sts = "0.23.0"
clap = { version = "4.1.4", features = ["derive", "env"] }
tokio = { version = "1.24.2", features = ["full"] }

[dev-dependencies]
aws-smithy-client = { version = "0.53.1", features = ["test-util"]}
aws-smithy-http = "0.53.1"
http = "0.2.8"
