[package]
name = "aws-mfa"
version = "1.0.8"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "mfa", "2fa"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aws-mfa"
documentation = "https://docs.rs/aws-mfa"
description = "Authenticate to AWS with MFA 🔐"

[lib]
name = "aws_mfa"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aws-mfa"
test = false
doc = false

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-credential-types = "1.0.1"
aws-sdk-sts = "1.3.1"
aws-smithy-runtime-api = "1.0.2"
clap = { version = "4.4.8", features = ["derive", "env"] }
http = "0.2.11"
thiserror = "1.0.50"
time = "0.3.30"
tokio = { version = "1.34.0", features = ["full"] }

[dev-dependencies]
aws-smithy-runtime = { version = "1.0.2", features = ["test-util"]}
aws-smithy-types = "1.0.1"
