[package]
name = "aws-mfa"
version = "0.2.1"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "mfa", "2fa"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aws-mfa"
description = """
Authenticate to AWS with MFA 🔐
"""

[lib]
name = "aws_mfa"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aws-mfa"
test = false
doc = false

[dependencies]
anyhow = "1.0.66"
aws-config = "0.51.0"
aws-sdk-sts = "0.21.0"
clap = { version = "4.0.22", features = ["derive", "env"] }
tokio = { version = "1.21.2", features = ["full"] }

[dev-dependencies]
aws-smithy-client = { version = "0.51.0", features = ["test-util"]}
aws-smithy-http = "0.51.0"
http = "0.2.8"