[package]
name = "aws-mfa"
version = "0.3.2"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "mfa", "2fa"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aws-mfa"
documentation = "https://docs.rs/aws-mfa"
description = "Authenticate to AWS with MFA 🔐"

[lib]
name = "aws_mfa"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aws-mfa"
test = false
doc = false

[dependencies]
anyhow = "1.0.71"
aws-config = "0.55.1"
aws-sdk-sts = "0.27.0"
clap = { version = "4.2.5", features = ["derive", "env"] }
tokio = { version = "1.28.0", features = ["full"] }

[dev-dependencies]
aws-smithy-client = { version = "0.55.2", features = ["test-util"]}
aws-smithy-http = "0.55.2"
aws-credential-types = "0.55.1"
http = "0.2.9"
