[package]
name = "aws-mfa"
version = "1.0.1"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "mfa", "2fa"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aws-mfa"
documentation = "https://docs.rs/aws-mfa"
description = "Authenticate to AWS with MFA 🔐"

[lib]
name = "aws_mfa"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aws-mfa"
test = false
doc = false

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
aws-config = "0.56.1"
aws-credential-types = "0.56.1"
aws-sdk-sts = "0.31.0"
aws-smithy-http = "0.56.1"
clap = { version = "4.4.3", features = ["derive", "env"] }
http = "0.2.9"
thiserror = "1.0.48"
time = "0.3.28"
tokio = { version = "1.32.0", features = ["full"] }

[dev-dependencies]
aws-smithy-client = { version = "0.56.1", features = ["test-util"]}
aws-smithy-types = "0.56.1"
