[package]
name = "aws-mfa"
version = "0.1.10"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "mfa", "2fa"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aws-mfa"
description = """
Authenticate to AWS with MFA 🔐
"""

[dependencies]
anyhow = "1.0.65"
aws-config = "0.49.0"
aws-sdk-sts = "0.19.0"
clap = { version = "4.0.9", features = ["derive", "env"] }
tokio = { version = "1.21.2", features = ["full"] }

[dev-dependencies]
aws-smithy-client = { version = "0.49.0", features = ["test-util"]}
aws-smithy-http = "0.49.0"
http = "0.2.8"
